name: multi-jobs Pipeline or workflow
on: push

jobs:
  buld_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout part
        uses: actions/checkout@v5

      - name: install commands and create files
        run: |
          sudo apt update
          sudo apt install tree -y
        
      - name: create folder and files using script
        run: |
          chmod +x multiple_josb.sh
          ./multiple_josb.sh
        
    
      - name: Upload Artifacts into test
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ./test_demo/**/*
            ./demo_test/**/*
        

  test_job_2:
    runs-on: ubuntu-latest
    needs: buld_job_1
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v5
        with:
            name: build-artifacts
      
      - name: List Directory demo_test
        run: |
          pwd
          ls -la

      - name: verify demo_test files content
        run: |
          pwd && ls -ll
          cd demo_test
          cat file{1..3}.txt

      - name: List Directory test_demo
        run: |
          cd ..
          ls -ltra

      - name: verify test_demo files content
        run: |
          cd test_demo
          ls -ltra
          cat file{1..3}.txt


  deploy_job_3:
    runs-on: ubuntu-latest
    needs: test_job_2
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v5
        with:
            name: build-artifacts
            
      - name: deploying files
        run: |
          sudo apt install tree -y
          tree
      
      - name: list files and deploying into /HOME directory
        run: |
          cp -r ./test_demo $HOME
          cp -r ./demo_test $HOME
          cd $HOME
          pwd
          ls -ltra
      
      - name: identify the files
        run: |
          ls -ltra test_demo
          ls -ltra demo_test
          
      - name: delete build files
        run: |
          rm -rf $GITHUB_WORKSPACE/test_demo
          rm -rf $GITHUB_WORKSPACE/demo_test

          ls -ltra $GITHUB_WORKSPACE
        

