name: my-test-workflow

on: push

jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
      - name: welcome message
        run: echo "My test first message"
        
      - name: list files
        run: ls -ltra

      - name: read files
        run: cat README.md
        
              